name: Deploy
on:
  push:
    branches:
      - main
jobs:
  ExperimentalJob:
    name: Experimental job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Print current folder"
        run: pwd
      - name: "List all files"
        run: ls .. -al
      - name: "Run deployment script"
        run: scripts/deploy.bat
