name: Deploy

on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "list files"
        run: ls
      - name: "Deploy"
        run: scripts/deploy.bat
