name: Deploy
on:
  push:
    branches:
      - main
jobs:
  ExperimentalJob:
    name: Experimental job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: "Run deployment script"
        shell: pwsh
        run: scripts/deploy.ps1
